### ISSUE TITLE
Options example showing how to ref .htmllintrc

### ISSUE THREAD

**Issue by robertbaker** [bezoerb/gulp-htmlhint#10]
It would be nice if you gave a code example how to specify the path to the .htmllintrc.

**Comment by bezoerb** [comment]
https://github.com/bezoerb/gulp-htmlhint/commit/609cdeddff7bd47f041f1b7d6177879a85e964c5

**Comment by bezoerb** [comment]
Done. For now, the path needs to be specified relative to the project root.

**Comment by bezoerb** [comment]
https://github.com/bezoerb/gulp-htmlhint/issues/11
