### ISSUE TITLE
Added Gulp task, nothing happens

### ISSUE THREAD

**Issue by caneta** [bezoerb/gulp-htmlhint#22]
Hi @bezoerb .
I made a Gulp task as follows:

```
var htmlhint     = require('gulp-htmlhint');
gulp.task('htmlhint', function() {
  return gulp.src('build/html/*.html')
    .pipe(htmlhint());
});
```

But if I create a broken html in my _build/html_, nothing is reported.

Any idea?

**Comment by bezoerb** [comment]
@caneta sorry for the late response. I'm quite busy at the moment but i'll try to take a look in the next days

**Comment by caneta** [comment]
Ok, thanks!

**Comment by dpilafian** [comment]
Pipe the `htmlhint()` output to the `reporter()` and you'll see the HTML errors.

**gulpfile.js**
```js
const htmlHint = require('gulp-htmlhint');

gulp.task('htmlHint', () => {
   return gulp.src('build/html/*.html')
      .pipe(htmlHint())
      .pipe(htmlHint.reporter());  //add this line to output the report
   });
```

**Comment by bezoerb** [comment]
Thanks @dpilafian!
