### ISSUE TITLE
‼️ minimatch security vulnerabilities

### ISSUE THREAD

**Issue by tjkohli** [bezoerb/gulp-htmlhint#41]
Heading | Description
--- | ---
| High | Regular Expression Denial of Service |
| Package | minimatch |
|Patched in | `>=3.0.2` |
|Dependency of | gulp-htmlhint [dev] |
| Path | `gulp-htmlhint > htmlhint > jshint > cli > glob > minimatch` |
| More info | https://nodesecurity.io/advisories/118 |

Heading | Description
--- | ---
| High | Regular Expression Denial of Service |
| Package | minimatch |
|Patched in |` >=3.0.2` |
|Dependency of | gulp-htmlhint [dev] |
| Path | `gulp-htmlhint > htmlhint > jshint > minimatch` |
| More info | https://nodesecurity.io/advisories/118 |

**Comment by bezoerb** [comment]
Should be fixed in [v2.2.1](https://github.com/bezoerb/gulp-htmlhint/releases/tag/v2.2.1)
