### ISSUE TITLE
Use htmlhint v1 as a peer dependency?

### ISSUE THREAD

**Issue by akrawitz** [bezoerb/gulp-htmlhint#67]
`htmlhint` is now on `v1.1.2`.

Could you please update to the latest version?

Ideally, I think `htmlhint` should be a peer dependency, so that users can pickup the latest version without you needing to manually update every time (or at least you would only need to intervene on major version changes).

Thanks!

**Comment by bezoerb** [comment]
https://github.com/bezoerb/gulp-htmlhint/releases/tag/v4.0.2
