### ISSUE TITLE
Without dest it process only 16 files

### ISSUE THREAD

**Issue by danielhusar** [bezoerb/gulp-htmlhint#7]
Hi,

If I use this task like this:

``` javascript
gulp.src("./src/*.html")
    .pipe(htmlhint())
    .pipe(htmlhint.reporter())
```

the htmlhint() will get all the files, but htmlhint.reporter() only first 16.
If I pipe pipe(gulp.dest('./src/')) it works fine.
Also if I pipe other plugins they works fine, just htmlhint.reporter() get only first 16 without 
pipe(gulp.dest('./src/'))

There was some similiar issue recently in gulp https://github.com/gulpjs/gulp/issues/552 but Im not sure if this is related as it is happenning only for htmlhint.reporter();

**Comment by GinMu** [comment]
Hi,
I have the same issue,my directory has more than 16 html files and other files. when I run gulp,the htmlhint() task only check first 16 html files but does not check the 17th html file.
thank you!
