### ISSUE TITLE
Ignore PHP tags

### ISSUE THREAD

**Issue by olivertappin-np** [bezoerb/gulp-htmlhint#8]
When validation phtml files or php files with HTML inside, it would be great if this plugin could ignore anything inside php tags `<?php`, `<?`, `<?=` so the rest of the page can be validated correctly without throwing the error: Special characters must be escaped : [ < ]. (spec-char-escape)

**Comment by bezoerb** [comment]
Good idea, i totally agree.
I'm quite busy at the moment so it will take me a while to implement this. PR's welcome ;)

**Comment by olivertappin-np** [comment]
I'll see if I can nail down a PR over the weekend.

**Comment by bezoerb** [comment]
:+1:

**Comment by hivre** [comment]
would love to see this!

**Comment by bezoerb** [comment]
i think evaluating the php files would a better, less error prone approach.
You could use `gulp-php2html` for this
