### ISSUE TITLE
error thrown using FailReporter

### ISSUE THREAD

**Issue by hivre** [bezoerb/gulp-htmlhint#9]
When running a document with errors, using `htmlhint.failReporter()`  I get the following:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: HTMLHint failed for: index.html

using the normal reporter I get actual errors shown. Not sure how I can get more info on this.
using: latest Ubuntu, npm v.2.6.1, node v.0.10.33

**Comment by bezoerb** [comment]
@hivre the failReporter throws a `PluginError` which should be handled by the application.
The error message however should give you more information when using the latest version.

**Comment by hivre** [comment]
thanks! I'll start looking into it

**Comment by bezoerb** [comment]
@hivre any updates on this? Could you resolve your issue?

**Comment by bezoerb** [comment]
Closed due lack of feedback.
Feel free to reopen if the error still exists
